# Generated by Django 4.1.5 on 2023-02-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('virtul_amount', models.FloatField(blank=True, null=True)),
                ('start_date', models.CharField(blank=True, max_length=45, null=True)),
                ('end_date', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cm_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonAgro',
            fields=[
                ('id_na', models.AutoField(primary_key=True, serialize=False)),
                ('commodity', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('change_per', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'non_agro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonAgroProducts',
            fields=[
                ('id_nap', models.AutoField(primary_key=True, serialize=False)),
                ('instrument', models.CharField(blank=True, max_length=45, null=True)),
                ('commodity', models.CharField(blank=True, max_length=45, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=45, null=True)),
                ('option_type', models.CharField(blank=True, max_length=45, null=True)),
                ('strike_price', models.FloatField(blank=True, null=True)),
                ('unit', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('ltp', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('abs_change', models.FloatField(blank=True, null=True)),
                ('vol', models.FloatField(blank=True, null=True)),
                ('oi', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('premium_to', models.FloatField(blank=True, null=True)),
                ('ul_product_ltp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'non_agro_products',
                'managed': False,
            },
        ),
    ]
